export enum ACCOUNT_STATEMENT_TRACKING_TABLE {
  TABLE_NAME = "SCC_SEGUIMIENTO_CUENTA_COBRO",
  ID = "SCC_CODIGO",
  OBSERVATION = "SCC_OBSERVACION",
  TRACKING_DATE = "SCC_FECHA_SEGUIMIENTO",
  STATUS = "SCC_ESTADO",
  FK_ACCOUNT_STATEMENT = "SCC_CODCTC_CUENTAS_COBRO",
}
