export enum PERMISSIONS {
  //=============================================
  // BUSINESS
  BUSINESS_CONSULT = "RAZON_SOCIAL_CONSULTAR",
  BUSINESS_CREATE = "RAZON_SOCIAL_CREAR",
  BUSINESS_UPDATE = "RAZON_SOCIAL_EDITAR",
  BUSINESS_DELETE = "RAZON_SOCIAL_ELIMINAR",
  //=============================================
  // CONTRACT
  CONTRACT_CONSULT = "CONTRATO_CONSULTAR",
  CONTRACT_CREATE = "CONTRATO_CREAR",
  CONTRACT_UPDATE = "CONTRATO_EDITAR",
  CONTRACT_DELETE = "CONTRATO_ELIMINAR",
  //=============================================
  // ACCOUNT STATEMENT
  ACCOUNT_STATEMENT_DETAIL = "CUENTA_COBRO_DETALLE",
  ACCOUNT_STATEMENT_CONSULT = "CUENTA_COBRO_CONSULTAR",
  ACCOUNT_STATEMENT_CREATE = "CUENTA_COBRO_CREAR",
  ACCOUNT_STATEMENT_UPDATE = "CUENTA_COBRO_EDITAR",
  ACCOUNT_STATEMENT_DELETE = "CUENTA_COBRO_ELIMINAR",
  ACCOUNT_STATEMENT_PDF = "CUENTA_COBRO_PDF",
  ACCOUNT_STATEMENT_EXCEL = "CUENTA_COBRO_EXCEL",
  //=============================================
  // ACCOUNT STATEMENT TRACKING
  ACCOUNT_STATEMENT_TRACKING_CONSULT = "SEGUIMIENTO_CUENTA_COBRO_CONSULTAR",
  ACCOUNT_STATEMENT_TRACKING_UPDATE = "SEGUIMIENTO_CUENTA_COBRO_EDITAR",
  //=============================================
  // FURNITURE
  FURNITURE_CONSULT = "BIEN_MUEBLE_CONSULTAR",
  FURNITURE_CREATE = "BIEN_MUEBLE_CREAR",
  FURNITURE_DETAIL = "BIEN_MUEBLE_DETALLE",
  FURNITURE_UPDATE = "BIEN_MUEBLE_EDITAR",
}
