export enum ASSETS_INVENTORY_TABLE {
  TABLE_NAME = "ACI_ACTIVOS_INVENTARIADOS",
  ID = "ACI_CODIGO",
  FK_ASSET = "ACI_CODACT_ACTIVO",
  USER_CREATED = "ACI_USUARIO",
  CREATED_AT = "ACI_FECHA",
  HOUR = "ACI_HORA",
}
