export enum ASSETS_HISTORY_TABLE {
  TABLE_NAME = "ACH_ACTIVOS_HISTORICO",
  ID = "ACH_CODIGO",
  USER_MODIFIED = "ACH_USUARIO",
  DATE_MODIFIED = "ACH_FECHA",
  UPDATED_FIELDS = "ACH_DATOS_MODIFICADOS",
  FK_ASSET = "ACH_CODACT_ACTIVO",
}
