export enum FURNITURE_INVENTORY_TABLE {
  TABLE_NAME = "IIN_INMUEBLES_INVENTARIADOS",
  ID = "IIN_CODIGO",
  FK_FURNITURE = "IIN_CODBIE_INMUEBLE",
  USER_CREATED = "IIN_USUARIO",
  CREATED_AT = "IIN_FECHA",
  HOUR = "IIN_HORA",
}
